// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetPairedDevices() {
  return window['go']['main']['App']['GetPairedDevices']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetTransferHistory() {
  return window['go']['main']['App']['GetTransferHistory']();
}

export function RegenerateQR() {
  return window['go']['main']['App']['RegenerateQR']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function ToggleServerStatus() {
  return window['go']['main']['App']['ToggleServerStatus']();
}
