// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDeviceInfo():Promise<Record<string, any>>;

export function GetPairedDevices():Promise<Array<main.PairedDevice>>;

export function GetQRCode():Promise<string>;

export function GetServerStatus():Promise<Record<string, any>>;

export function GetTransferHistory():Promise<Array<main.TransferRecord>>;

export function RegenerateQR():Promise<string>;

export function TestConnection():Promise<string>;

export function ToggleServerStatus():Promise<boolean>;
